import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react';
import App from '../components/App';

const Home: NextPage = () => {
  return (
    <div id={"root"}>
      <Head>
        <title>take44444&apos;s Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/logo192.png" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <App />
    </div>
  )
}

export default Home
